/*
TrustCheck.cpp - 用于检查程序的数字签名是否有效
Licensed under the MIT License (MIT)
* Notice: Some code is generated by ChatGPT.

The MIT License (MIT)
Copyright © 2026 shc0743<github.com/shc0743>

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the “Software”), to deal
in the Software without restriction, including without limitation the rights 
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
of the Software, and to permit persons to whom the Software is furnished to do 
so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all 
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE 
SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

Fork this project to create your own MIT license that you can always link to.
*/

#include "TrustCheck.hpp"

#include <softpub.h>
#include <wtsapi32.h>

#include <array>
#include <string>
#include <vector>
#include <memory>
#include <algorithm>
#include <cwchar>

#pragma comment(lib, "wintrust.lib")
#pragma comment(lib, "crypt32.lib")
#pragma comment(lib, "wtsapi32.lib")

namespace
{
	constexpr DWORD kEncodingType =
		X509_ASN_ENCODING | PKCS_7_ASN_ENCODING;

	// SafeCheck 用于取得 TrustCheck 最后一次失败原因。
	thread_local LONG g_lastTrustError = ERROR_SUCCESS;


	// ------------------------------------------------------------------------
	// RAII helpers
	// ------------------------------------------------------------------------

	struct CertStoreDeleter
	{
		void operator()(HCERTSTORE h) const noexcept
		{
			if (h)
				CertCloseStore(h, 0);
		}
	};

	struct CertContextDeleter
	{
		void operator()(PCCERT_CONTEXT p) const noexcept
		{
			if (p)
				CertFreeCertificateContext(p);
		}
	};

	struct CertChainEngineDeleter
	{
		void operator()(HCERTCHAINENGINE h) const noexcept
		{
			if (h)
				CertFreeCertificateChainEngine(h);
		}
	};

	struct CertChainDeleter
	{
		void operator()(PCCERT_CHAIN_CONTEXT p) const noexcept
		{
			if (p)
				CertFreeCertificateChain(p);
		}
	};

	struct CryptMsgDeleter
	{
		void operator()(HCRYPTMSG h) const noexcept
		{
			if (h)
				CryptMsgClose(h);
		}
	};


	// ------------------------------------------------------------------------
	// Get current executable path
	// ------------------------------------------------------------------------

	static std::wstring GetProgramFullName()
	{
		std::vector<wchar_t> buffer(512);

		for (;;)
		{
			DWORD len = GetModuleFileNameW(
				nullptr,
				buffer.data(),
				static_cast<DWORD>(buffer.size()));

			if (len == 0)
				return {};

			if (len < buffer.size() - 1)
				return std::wstring(buffer.data(), len);

			// Buffer probably too small.
			buffer.resize(buffer.size() * 2);

			// 防止理论上的整数溢出。
			if (buffer.size() > 32768)
				return {};
		}
	}


	static std::wstring GetProgramExecutableName()
	{
		std::wstring path = GetProgramFullName();

		if (path.empty())
			return L"";

		const size_t pos = path.find_last_of(L"\\/");

		if (pos == std::wstring::npos)
			return path;

		return path.substr(pos + 1);
	}


	// ------------------------------------------------------------------------
	// Format Windows / HRESULT error
	// ------------------------------------------------------------------------

	static std::wstring ErrorCodeToStringW(LONG errorCode)
	{
		wchar_t* buffer = nullptr;

		DWORD flags =
			FORMAT_MESSAGE_ALLOCATE_BUFFER |
			FORMAT_MESSAGE_FROM_SYSTEM |
			FORMAT_MESSAGE_IGNORE_INSERTS;

		DWORD len = FormatMessageW(
			flags,
			nullptr,
			static_cast<DWORD>(errorCode),
			0,
			reinterpret_cast<LPWSTR>(&buffer),
			0,
			nullptr);

		if (!len || !buffer)
		{
			wchar_t fallback[32]{};

			swprintf_s(
				fallback,
				L"0x%08lX",
				static_cast<unsigned long>(
					static_cast<DWORD>(errorCode)));

			return fallback;
		}

		// 去掉 FormatMessage 自动附带的 CR/LF。
		while (len > 0 &&
			(buffer[len - 1] == L'\r' ||
				buffer[len - 1] == L'\n' ||
				buffer[len - 1] == L' '))
		{
			--len;
		}

		std::wstring result(buffer, len);

		LocalFree(buffer);

		return result;
	}


	// ------------------------------------------------------------------------
	// Verify the actual Authenticode signature
	// ------------------------------------------------------------------------

	static LONG VerifyAuthenticodeSignature(
		LPCWSTR filePath)
	{
		WINTRUST_FILE_INFO fileInfo{};
		fileInfo.cbStruct = sizeof(fileInfo);
		fileInfo.pcwszFilePath = filePath;

		WINTRUST_DATA trustData{};
		trustData.cbStruct = sizeof(trustData);

		trustData.dwUIChoice = WTD_UI_NONE;

		// 对你的自签 Root 场景来说，CRL/OCSP 本身没有太大意义。
		trustData.fdwRevocationChecks = WTD_REVOKE_NONE;

		trustData.dwUnionChoice = WTD_CHOICE_FILE;
		trustData.pFile = &fileInfo;

		trustData.dwStateAction = WTD_STATEACTION_VERIFY;

		// 不因为网络证书获取导致这里出现网络访问。
		trustData.dwProvFlags =
			WTD_CACHE_ONLY_URL_RETRIEVAL;

		GUID policy = WINTRUST_ACTION_GENERIC_VERIFY_V2;

		LONG status = WinVerifyTrust(
			nullptr,
			&policy,
			&trustData);

		// 清理 WinTrust 状态。
		trustData.dwStateAction = WTD_STATEACTION_CLOSE;

		WinVerifyTrust(
			nullptr,
			&policy,
			&trustData);

		return status;
	}


	// ------------------------------------------------------------------------
	// Extract signer certificate from embedded PKCS#7
	// ------------------------------------------------------------------------

	static PCCERT_CONTEXT GetSignerCertificate(
		LPCWSTR filePath,
		HCERTSTORE* outStore,
		HCRYPTMSG* outMsg)
	{
		if (!outStore || !outMsg)
			return nullptr;

		*outStore = nullptr;
		*outMsg = nullptr;

		DWORD encodingType = 0;
		DWORD contentType = 0;
		DWORD formatType = 0;

		HCERTSTORE store = nullptr;
		HCRYPTMSG msg = nullptr;

		BOOL ok = CryptQueryObject(
			CERT_QUERY_OBJECT_FILE,
			filePath,

			// 这里明确要求 embedded PKCS#7。
			CERT_QUERY_CONTENT_FLAG_PKCS7_SIGNED_EMBED,

			CERT_QUERY_FORMAT_FLAG_ALL,

			0,

			&encodingType,
			&contentType,
			&formatType,
			&store,
			&msg,
			nullptr);

		if (!ok)
			return nullptr;


		DWORD signerInfoSize = 0;

		ok = CryptMsgGetParam(
			msg,
			CMSG_SIGNER_CERT_INFO_PARAM,
			0,
			nullptr,
			&signerInfoSize);

		if (!ok || signerInfoSize == 0)
		{
			CryptMsgClose(msg);
			CertCloseStore(store, 0);
			return nullptr;
		}


		std::vector<uint8_t> signerInfo(
			signerInfoSize);

		ok = CryptMsgGetParam(
			msg,
			CMSG_SIGNER_CERT_INFO_PARAM,
			0,
			signerInfo.data(),
			&signerInfoSize);

		if (!ok)
		{
			CryptMsgClose(msg);
			CertCloseStore(store, 0);
			return nullptr;
		}


		PCCERT_CONTEXT signerCert =
			CertGetSubjectCertificateFromStore(
				store,
				kEncodingType,
				reinterpret_cast<PCERT_INFO>(
					signerInfo.data()));

		if (!signerCert)
		{
			CryptMsgClose(msg);
			CertCloseStore(store, 0);
			return nullptr;
		}


		*outStore = store;
		*outMsg = msg;

		return signerCert;
	}


	// ------------------------------------------------------------------------
	// Compare two certificate DER blobs exactly
	// ------------------------------------------------------------------------

	static bool CertificateEquals(
		PCCERT_CONTEXT a,
		PCCERT_CONTEXT b)
	{
		if (!a || !b)
			return false;

		if (a->cbCertEncoded != b->cbCertEncoded)
			return false;

		return std::equal(
			a->pbCertEncoded,
			a->pbCertEncoded + a->cbCertEncoded,
			b->pbCertEncoded);
	}


	// ------------------------------------------------------------------------
	// Verify signer -> trustedRoot
	// ------------------------------------------------------------------------

	static LONG VerifyCertificateChainToPinnedRoot(
		PCCERT_CONTEXT signerCert,
		HCERTSTORE additionalStore,
		const uint8_t* trustedRootDer,
		size_t trustedRootDerSize)
	{
		if (!signerCert ||
			!trustedRootDer ||
			trustedRootDerSize == 0)
		{
			return ERROR_INVALID_PARAMETER;
		}


		// ================================================================
		// 1. 创建只包含我们信任 Root 的 exclusive root store
		// ================================================================

		HCERTSTORE rawRootStore = CertOpenStore(
			CERT_STORE_PROV_MEMORY,
			0,
			0,
			CERT_STORE_CREATE_NEW_FLAG,
			nullptr);

		if (!rawRootStore)
			return static_cast<LONG>(GetLastError());

		std::unique_ptr<
			std::remove_pointer_t<HCERTSTORE>,
			CertStoreDeleter> rootStore(
				rawRootStore);


		PCCERT_CONTEXT rawPinnedRoot =
			CertCreateCertificateContext(
				X509_ASN_ENCODING,
				trustedRootDer,
				static_cast<DWORD>(trustedRootDerSize));

		if (!rawPinnedRoot)
			return static_cast<LONG>(GetLastError());


		std::unique_ptr<
			const CERT_CONTEXT,
			CertContextDeleter> pinnedRoot(
				rawPinnedRoot);


		if (!CertAddCertificateContextToStore(
			rootStore.get(),
			pinnedRoot.get(),
			CERT_STORE_ADD_REPLACE_EXISTING,
			nullptr))
		{
			return static_cast<LONG>(GetLastError());
		}


		// ================================================================
		// 2. 创建 Exclusive Trust chain engine
		// ================================================================

		CERT_CHAIN_ENGINE_CONFIG config{};

		config.cbSize = sizeof(config);

		// 这是关键。
		//
		// Windows 系统自己的 Root store 在 exclusive trust mode
		// 中不会作为 trust anchor。
		//
		config.hExclusiveRoot =
			rootStore.get();

		// 允许使用签名里附带的 intermediate certificates。
		HCERTSTORE additionalStores[1] =
		{
			additionalStore
		};

		config.cAdditionalStore = 1;
		config.rghAdditionalStore =
			additionalStores;

		// 不主动通过网络抓 AIA。
		config.dwFlags =
			CERT_CHAIN_DISABLE_AIA |
			CERT_CHAIN_CACHE_ONLY_URL_RETRIEVAL;


		HCERTCHAINENGINE rawEngine = nullptr;

		if (!CertCreateCertificateChainEngine(
			&config,
			&rawEngine))
		{
			return static_cast<LONG>(GetLastError());
		}

		std::unique_ptr<
			std::remove_pointer_t<HCERTCHAINENGINE>,
			CertChainEngineDeleter> engine(
				rawEngine);


		// ================================================================
		// 3. 要求 signer 用于 Code Signing
		// ================================================================

		CHAR codeSigningOid[] = szOID_PKIX_KP_CODE_SIGNING;

		LPSTR usage[] =
		{
			codeSigningOid
		};

		CERT_CHAIN_PARA chainPara{};

		chainPara.cbSize = sizeof(chainPara);

		chainPara.RequestedUsage.dwType =
			USAGE_MATCH_TYPE_AND;

		chainPara.RequestedUsage.Usage.cUsageIdentifier = 1;

		chainPara.RequestedUsage.Usage.rgpszUsageIdentifier =
			usage;


		// ================================================================
		// 4. 构建 signer -> Root chain
		// ================================================================

		PCCERT_CHAIN_CONTEXT rawChain = nullptr;

		if (!CertGetCertificateChain(
			engine.get(),
			signerCert,
			nullptr,
			additionalStore,
			&chainPara,
			0,
			nullptr,
			&rawChain))
		{
			return static_cast<LONG>(GetLastError());
		}

		std::unique_ptr<
			const CERT_CHAIN_CONTEXT,
			CertChainDeleter> chain(
				rawChain);


		if (!chain ||
			chain->cChain == 0 ||
			!chain->rgpChain[0])
		{
			return CERT_E_CHAINING;
		}


		PCERT_SIMPLE_CHAIN simpleChain =
			chain->rgpChain[0];


		if (!simpleChain ||
			simpleChain->cElement == 0)
		{
			return CERT_E_CHAINING;
		}


		// ================================================================
		// 5. 检查整个 chain 是否存在错误
		// ================================================================

		for (DWORD i = 0;
			i < simpleChain->cElement;
			++i)
		{
			const CERT_CHAIN_ELEMENT* element =
				simpleChain->rgpElement[i];

			if (!element)
				return CERT_E_CHAINING;

			if (element->TrustStatus.dwErrorStatus !=
				CERT_TRUST_NO_ERROR)
			{
				return static_cast<LONG>(
					element->TrustStatus.dwErrorStatus);
			}
		}


		// ================================================================
		// 6. 强制 chain 最后一个证书 == 我们预置的 Root
		// ================================================================

		PCCERT_CONTEXT chainRoot =
			simpleChain->rgpElement[
				simpleChain->cElement - 1
			]->pCertContext;

		if (!CertificateEquals(
			chainRoot,
			pinnedRoot.get()))
		{
			return CERT_E_UNTRUSTEDROOT;
		}


		// ================================================================
		// 7. 再走 Authenticode chain policy
		// ================================================================

		CERT_CHAIN_POLICY_PARA policyPara{};

		policyPara.cbSize =
			sizeof(policyPara);

		CERT_CHAIN_POLICY_STATUS policyStatus{};

		policyStatus.cbSize =
			sizeof(policyStatus);

		if (!CertVerifyCertificateChainPolicy(
			CERT_CHAIN_POLICY_AUTHENTICODE,
			chain.get(),
			&policyPara,
			&policyStatus))
		{
			return static_cast<LONG>(
				GetLastError());
		}

		if (policyStatus.dwError != 0)
		{
			return static_cast<LONG>(
				policyStatus.dwError);
		}


		return ERROR_SUCCESS;
	}


	// ------------------------------------------------------------------------
	// Internal implementation
	// ------------------------------------------------------------------------

	static LONG TrustCheckInternal(
		const uint8_t* trustedRootDer,
		size_t trustedRootDerSize,
		bool validateCertificateChainRoot)
	{
		const std::wstring filePath =
			GetProgramFullName();

		if (filePath.empty())
			return ERROR_FILE_NOT_FOUND;


		// ================================================================
		// 第一层：
		// 检查 EXE 的 Authenticode 签名
		// ================================================================

		LONG authenticodeStatus =
			VerifyAuthenticodeSignature(
				filePath.c_str());

		if (authenticodeStatus != ERROR_SUCCESS)
		{
			// Windows 系统证书库不认识我们自己的 Root CA，
			// 因此 WinVerifyTrust 可能返回以下错误。
			//
			// 这些错误不能直接认为“文件签名坏了”。
			// 后面还会使用我们自己内置的 Root CA 重新建立链。
			switch (authenticodeStatus)
			{
			case CERT_E_CHAINING:
			case CERT_E_UNTRUSTEDROOT:
			case CERT_E_UNTRUSTEDCA:
				break;

			default:
				// 例如：
				// TRUST_E_NO_SIGNATURE
				// TRUST_E_BAD_DIGEST
				// CERT_E_INVALID_SIGNATURE
				// 等真正的签名/文件完整性错误
				//
				// 直接失败。
				return authenticodeStatus;
			}
		}


		// ================================================================
		// 如果用户明确关闭 Root 校验，则只保留 Authenticode 校验。
		//
		// 不建议生产版本这么使用。
		// ================================================================

		if (!validateCertificateChainRoot)
		{
			return ERROR_SUCCESS;
		}


		if (!trustedRootDer ||
			trustedRootDerSize == 0)
		{
			return ERROR_INVALID_PARAMETER;
		}


		// ================================================================
		// 第二层：
		// 提取 signer certificate
		// ================================================================

		HCERTSTORE rawStore = nullptr;
		HCRYPTMSG rawMsg = nullptr;

		PCCERT_CONTEXT rawSigner =
			GetSignerCertificate(
				filePath.c_str(),
				&rawStore,
				&rawMsg);

		if (!rawSigner)
		{
			return static_cast<LONG>(
				GetLastError());
		}

		std::unique_ptr<
			std::remove_pointer_t<HCERTSTORE>,
			CertStoreDeleter> store(
				rawStore);

		std::unique_ptr<
			const CERT_CONTEXT,
			CertContextDeleter> signer(
				rawSigner);

		std::unique_ptr<
			std::remove_pointer_t<HCRYPTMSG>,
			CryptMsgDeleter> msg(
				rawMsg);


		// ================================================================
		// 第三层：
		// signer 必须链到我们自己的 Root
		// ================================================================

		LONG chainStatus =
			VerifyCertificateChainToPinnedRoot(
				signer.get(),
				store.get(),
				trustedRootDer,
				trustedRootDerSize);

		return chainStatus;
	}
}


// ============================================================================
// Public API
// ============================================================================

bool TrustCheck(
	const uint8_t* trustedRootDer,
	size_t trustedRootDerSize,
	bool validateCertificateChainRoot)
{
	g_lastTrustError =
		TrustCheckInternal(
			trustedRootDer,
			trustedRootDerSize,
			validateCertificateChainRoot);

	return g_lastTrustError == ERROR_SUCCESS;
}


// ============================================================================
// SafeCheck
// ============================================================================

int SafeCheck(
	const uint8_t* trustedRootDer,
	size_t trustedRootDerSize,
	bool validateCertificateChainRoot)
{
	static const wchar_t* const kErrorFromZh =
		L"错误来自%s";

	static const wchar_t* const kErrorTextZh =
		L"数字签名无效。文件已遭到篡改。请重新下载最新版本。\n"
		L"错误代码: 0x%08lX: %s";

	static const wchar_t* const kErrorFromEn =
		L"Error from %s";

	static const wchar_t* const kErrorTextEn =
		L"Digital signature is invalid. "
		L"The file has been damaged. "
		L"Please download the latest version again.\n"
		L"Error code: 0x%08lX: %s";


	std::wstring title;
	std::wstring text;


	// PRIMARYLANGID 返回的是用户 UI 语言。
	const LANGID lang =
		GetUserDefaultUILanguage();

	const WORD primary =
		PRIMARYLANGID(lang);

	const bool isChinese =
		primary == LANG_CHINESE;


	if (!TrustCheck(
		trustedRootDer,
		trustedRootDerSize,
		validateCertificateChainRoot))
	{
		const LONG errorCode =
			g_lastTrustError;


		const std::wstring exeName =
			GetProgramExecutableName();

		const std::wstring errorText =
			ErrorCodeToStringW(errorCode);


		wchar_t titleBuffer[512]{};
		wchar_t textBuffer[2048]{};


		if (isChinese)
		{
			swprintf_s(
				titleBuffer,
				kErrorFromZh,
				exeName.c_str());

			swprintf_s(
				textBuffer,
				kErrorTextZh,
				static_cast<unsigned long>(
					static_cast<DWORD>(errorCode)),
				errorText.c_str());
		}
		else
		{
			swprintf_s(
				titleBuffer,
				kErrorFromEn,
				exeName.c_str());

			swprintf_s(
				textBuffer,
				kErrorTextEn,
				static_cast<unsigned long>(
					static_cast<DWORD>(errorCode)),
				errorText.c_str());
		}


		DWORD response = 0;

		WTSSendMessageW(
			WTS_CURRENT_SERVER_HANDLE,
			WTS_CURRENT_SESSION,
			titleBuffer,
			static_cast<DWORD>(
				(wcslen(titleBuffer) + 1) *
				sizeof(wchar_t)),
			textBuffer,
			static_cast<DWORD>(
				(wcslen(textBuffer) + 1) *
				sizeof(wchar_t)),
			MB_ICONERROR,
			0,
			&response,
			TRUE);


		return ERROR_FILE_CORRUPT;
	}


	return ERROR_SUCCESS;
}

